# Generated by Django 4.2.7 on 2025-08-03 07:05

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('plan_type', models.CharField(choices=[('daily', 'Daily Plan'), ('weekly', 'Weekly Plan'), ('monthly', 'Monthly Plan'), ('custom', 'Custom Plan')], default='weekly', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='draft', max_length=20)),
                ('start_date', models.DateField()),
                ('target_end_date', models.DateField()),
                ('actual_end_date', models.DateField(blank=True, null=True)),
                ('total_estimated_hours', models.FloatField(default=0.0)),
                ('total_topics', models.PositiveIntegerField(default=0)),
                ('average_difficulty', models.FloatField(default=0.0)),
                ('completed_hours', models.FloatField(default=0.0)),
                ('completed_topics', models.PositiveIntegerField(default=0)),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('longest_streak', models.PositiveIntegerField(default=0)),
                ('daily_study_hours', models.FloatField(help_text='Planned daily study hours')),
                ('session_length', models.PositiveIntegerField(help_text='Study session length in minutes')),
                ('break_length', models.PositiveIntegerField(help_text='Break length in minutes')),
                ('difficulty_adjustment', models.FloatField(default=1.0, help_text='Difficulty multiplier based on performance')),
                ('time_adjustment', models.FloatField(default=1.0, help_text='Time multiplier based on actual vs estimated')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('syllabus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_plans', to='curriculum.syllabus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('block_type', models.CharField(choices=[('study', 'Study Session'), ('review', 'Review Session'), ('assessment', 'Assessment'), ('break', 'Break'), ('buffer', 'Buffer Time')], default='study', max_length=20)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('skipped', 'Skipped'), ('rescheduled', 'Rescheduled')], default='scheduled', max_length=20)),
                ('scheduled_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('estimated_duration', models.PositiveIntegerField(help_text='Duration in minutes')),
                ('actual_duration', models.PositiveIntegerField(blank=True, help_text='Actual duration in minutes', null=True)),
                ('completion_percentage', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('difficulty_rating', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('satisfaction_rating', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('notes', models.TextField(blank=True)),
                ('challenges_faced', models.JSONField(default=list)),
                ('achievements', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('learning_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_blocks', to='planning.learningplan')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_blocks', to='curriculum.topic')),
            ],
            options={
                'ordering': ['scheduled_date', 'start_time'],
                'unique_together': {('learning_plan', 'scheduled_date', 'start_time')},
            },
        ),
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('paused_duration', models.PositiveIntegerField(default=0, help_text='Total paused time in minutes')),
                ('focus_score', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('understanding_score', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('retention_confidence', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('concepts_mastered', models.JSONField(default=list)),
                ('concepts_struggling', models.JSONField(default=list)),
                ('questions_raised', models.JSONField(default=list)),
                ('resources_used', models.JSONField(default=list)),
                ('session_notes', models.TextField(blank=True)),
                ('next_session_goals', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('schedule_block', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='study_session', to='planning.scheduleblock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
