# Generated by Django 4.2.7 on 2025-08-03 07:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('retrying', 'Retrying')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('use_groq', models.BooleanField(default=True)),
                ('use_huggingface', models.BooleanField(default=True)),
                ('analysis_depth', models.CharField(choices=[('basic', 'Basic'), ('detailed', 'Detailed'), ('comprehensive', 'Comprehensive')], default='detailed', max_length=20)),
                ('total_topics_extracted', models.PositiveIntegerField(default=0)),
                ('average_confidence', models.FloatField(default=0.0)),
                ('processing_time_seconds', models.FloatField(default=0.0)),
                ('groq_model_used', models.CharField(blank=True, max_length=100)),
                ('huggingface_model_used', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('syllabus', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_job', to='curriculum.syllabus')),
            ],
        ),
        migrations.CreateModel(
            name='TopicAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ai_summary', models.TextField(help_text='AI-generated topic summary')),
                ('extracted_keywords', models.JSONField(default=list, help_text='AI-extracted keywords')),
                ('semantic_tags', models.JSONField(default=list, help_text='Semantic classification tags')),
                ('complexity_score', models.FloatField(help_text='AI-calculated complexity (0-1)')),
                ('cognitive_load', models.FloatField(help_text='Estimated cognitive load (0-1)')),
                ('prerequisite_complexity', models.FloatField(default=0.0, help_text='Prerequisites complexity impact')),
                ('reading_time_minutes', models.FloatField(default=0.0)),
                ('practice_time_minutes', models.FloatField(default=0.0)),
                ('mastery_time_minutes', models.FloatField(default=0.0)),
                ('review_time_minutes', models.FloatField(default=0.0)),
                ('visual_learning_score', models.FloatField(default=0.5, help_text='Visual learning suitability (0-1)')),
                ('auditory_learning_score', models.FloatField(default=0.5, help_text='Auditory learning suitability (0-1)')),
                ('kinesthetic_learning_score', models.FloatField(default=0.5, help_text='Kinesthetic learning suitability (0-1)')),
                ('reading_learning_score', models.FloatField(default=0.5, help_text='Reading/writing learning suitability (0-1)')),
                ('bloom_taxonomy_level', models.CharField(choices=[('remember', 'Remember'), ('understand', 'Understand'), ('apply', 'Apply'), ('analyze', 'Analyze'), ('evaluate', 'Evaluate'), ('create', 'Create')], default='understand', max_length=20)),
                ('topic_extraction_confidence', models.FloatField(default=0.0)),
                ('difficulty_confidence', models.FloatField(default=0.0)),
                ('time_estimation_confidence', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analysis_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_analyses', to='analysis.analysisjob')),
                ('topic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='curriculum.topic')),
            ],
        ),
    ]
