# Generated by Django 4.2.7 on 2025-08-03 09:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('schedule_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='weekly', max_length=20)),
                ('difficulty_progression', models.CharField(choices=[('linear', 'Linear Progression'), ('adaptive', 'Adaptive Progression'), ('spiral', 'Spiral Learning')], default='adaptive', max_length=20)),
                ('total_duration_days', models.PositiveIntegerField()),
                ('daily_study_hours', models.FloatField(validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(12)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('completion_percentage', models.FloatField(default=0.0)),
                ('learning_style_weights', models.JSONField(default=dict)),
                ('buffer_time_percentage', models.FloatField(default=20.0)),
                ('syllabus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.syllabus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TopicExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cognitive_level', models.CharField(choices=[('remember', 'Remember'), ('understand', 'Understand'), ('apply', 'Apply'), ('analyze', 'Analyze'), ('evaluate', 'Evaluate'), ('create', 'Create')], default='understand', max_length=20)),
                ('learning_objectives', models.JSONField(default=list)),
                ('recommended_resources', models.JSONField(default=list)),
                ('practice_exercises', models.JSONField(default=list)),
                ('visual_content_ratio', models.FloatField(default=0.3)),
                ('practical_application_ratio', models.FloatField(default=0.2)),
                ('theoretical_depth', models.FloatField(default=0.5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='learning_extension', to='curriculum.topic')),
            ],
        ),
        migrations.CreateModel(
            name='StudyPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_learning_style', models.CharField(choices=[('visual', 'Visual'), ('auditory', 'Auditory'), ('kinesthetic', 'Kinesthetic'), ('reading', 'Reading/Writing')], default='visual', max_length=20)),
                ('secondary_learning_style', models.CharField(blank=True, choices=[('visual', 'Visual'), ('auditory', 'Auditory'), ('kinesthetic', 'Kinesthetic'), ('reading', 'Reading/Writing')], max_length=20)),
                ('difficulty_preference', models.CharField(choices=[('easy_first', 'Easy Topics First'), ('hard_first', 'Challenging Topics First'), ('mixed', 'Mixed Difficulty'), ('adaptive', 'Adaptive Based on Performance')], default='adaptive', max_length=20)),
                ('preferred_study_time', models.CharField(choices=[('morning', 'Morning (6-12 AM)'), ('afternoon', 'Afternoon (12-6 PM)'), ('evening', 'Evening (6-10 PM)'), ('night', 'Night (10 PM-2 AM)'), ('flexible', 'Flexible')], default='flexible', max_length=20)),
                ('max_session_duration', models.PositiveIntegerField(default=90)),
                ('break_frequency', models.PositiveIntegerField(default=25)),
                ('break_duration', models.PositiveIntegerField(default=5)),
                ('long_break_duration', models.PositiveIntegerField(default=30)),
                ('spaced_repetition_enabled', models.BooleanField(default=True)),
                ('revision_frequency_days', models.PositiveIntegerField(default=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('milestone_type', models.CharField(choices=[('weekly', 'Weekly Checkpoint'), ('monthly', 'Monthly Review'), ('unit', 'Unit Completion'), ('exam', 'Exam Preparation'), ('project', 'Project Deadline')], max_length=20)),
                ('target_date', models.DateTimeField()),
                ('is_completed', models.BooleanField(default=False)),
                ('completion_percentage', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('learning_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='learning_plan.learningplan')),
                ('topics', models.ManyToManyField(related_name='milestones', to='curriculum.topic')),
            ],
            options={
                'ordering': ['target_date'],
            },
        ),
        migrations.CreateModel(
            name='LearningSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('study', 'Study Session'), ('review', 'Review Session'), ('practice', 'Practice Session'), ('assessment', 'Assessment')], default='study', max_length=20)),
                ('scheduled_date', models.DateTimeField()),
                ('estimated_duration_minutes', models.PositiveIntegerField()),
                ('actual_duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('skipped', 'Skipped'), ('rescheduled', 'Rescheduled')], default='pending', max_length=20)),
                ('difficulty_level', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('completion_score', models.FloatField(blank=True, null=True)),
                ('confidence_level', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('learning_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='learning_plan.learningplan')),
                ('prerequisites', models.ManyToManyField(blank=True, to='learning_plan.learningsession')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.topic')),
            ],
            options={
                'ordering': ['scheduled_date'],
            },
        ),
    ]
