# Generated by Django 4.2.7 on 2025-08-03 07:04

import curriculum.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to=curriculum.models.syllabus_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'doc', 'txt'])])),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('subject', models.CharField(choices=[('mathematics', 'Mathematics'), ('science', 'Science'), ('engineering', 'Engineering'), ('computer_science', 'Computer Science'), ('literature', 'Literature'), ('history', 'History'), ('languages', 'Languages'), ('business', 'Business'), ('arts', 'Arts'), ('other', 'Other')], default='other', max_length=30)),
                ('estimated_duration_weeks', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('analyzed', 'Analyzed'), ('completed', 'Plan Generated'), ('error', 'Error')], default='uploaded', max_length=20)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('processing_completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('extracted_text', models.TextField(blank=True, help_text='Raw extracted text from file')),
                ('cleaned_text', models.TextField(blank=True, help_text='Processed and cleaned text')),
                ('word_count', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllabi', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Syllabi',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('topic_type', models.CharField(choices=[('concept', 'Core Concept'), ('skill', 'Practical Skill'), ('theory', 'Theoretical Knowledge'), ('application', 'Application/Practice'), ('assessment', 'Assessment/Test'), ('project', 'Project Work'), ('reading', 'Reading Assignment')], default='concept', max_length=20)),
                ('difficulty_level', models.PositiveIntegerField(choices=[(1, 'Very Easy'), (2, 'Easy'), (3, 'Easy-Medium'), (4, 'Medium'), (5, 'Medium-Hard'), (6, 'Hard'), (7, 'Very Hard'), (8, 'Expert'), (9, 'Master'), (10, 'Extreme')], default=5)),
                ('estimated_hours', models.FloatField(help_text='Estimated study hours required')),
                ('confidence_score', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('key_concepts', models.JSONField(default=list, help_text='List of key concepts in this topic')),
                ('learning_objectives', models.JSONField(default=list, help_text='Learning objectives for this topic')),
                ('suggested_resources', models.JSONField(default=list, help_text='Suggested learning resources')),
                ('order_index', models.PositiveIntegerField(default=0, help_text='Order within syllabus')),
                ('chapter_section', models.CharField(blank=True, help_text='Chapter or section reference', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prerequisites', models.ManyToManyField(blank=True, related_name='dependents', to='curriculum.topic')),
                ('syllabus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='curriculum.syllabus')),
            ],
            options={
                'ordering': ['order_index', 'created_at'],
                'unique_together': {('syllabus', 'order_index')},
            },
        ),
    ]
